version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swe304
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sbnet

  web-app:
    container_name: jenkins
    image: devopsj
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swe304
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      S3_ENDPOINT: http://s3.amazonaws.com
      S3_ACCESS_KEY: AKIA4TS3WBWNCHCMPCRN
      S3_SECRET_KEY: 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
    ports:
      - "8080:8080"  # Correctly map the port
    networks:
      - sbnet

volumes:
  postgres_data:

networks:
  sbnet:
    driver: bridge
    external: true
