apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 8080
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: swe304/web-app:latest
          ports:
            - containerPort: 8080
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: person
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: password