apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      name: web-app
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: swe304/web-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: person
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: password