apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32140
      protocol: TCP
  type: NodePort